// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaeorurdxfnfuowyrvpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhZW9ydXJkeGZuZnVvd3lydnB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODIyNDgsImV4cCI6MjA2ODY1ODI0OH0.A23wffLG_9YoEQk9T0HXINgOu_qrO4PY9KwdytbCbk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});